[versions]
accompanist-systemuicontroller = "0.35.1-alpha"
activity-compose = "1.9.0"
# @pin so this is not updated to alpha versions
agp = "8.4.1"
androidx-test-ext-junit = "1.2.0-rc01"
app-turbine = "1.1.0"
coil-compose = "2.6.0"
#compose-bom = "2023.10.01"
compose-bom = "2024.05.00-alpha03"
core-ktx = "1.14.0-alpha01"
datastore = "1.1.1"
espresso-core = "3.6.0-rc01"
hilt = "2.51.1"
junit = "4.13.2"
kotlin = "2.0.0"
kotlinx-coroutines-test = "1.9.0-RC"
kotlinx-serialization-json = "1.7.0-RC"
lazytable = "1.8.0"
lifecycle-runtime-ktx = "2.8.1"
reorderable = "0.9.6"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
app-turbine = { module = "app.cash.turbine:turbine", version.ref = "app-turbine" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
#compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-bom = { module = "dev.chrisbanes.compose:compose-bom", version.ref = "compose-bom" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-kapt = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation = "androidx.hilt:hilt-navigation-compose:1.2.0"
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lazytable = { module = "io.github.oleksandrbalan:lazytable", version.ref = "lazytable" }
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
# ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material3 = { module = "androidx.compose.material3:material3" }
reorderable = { module = "org.burnoutcrew.composereorderable:reorderable", version.ref = "reorderable" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-util = { module = "androidx.compose.ui:ui-util" }

[bundles]
hilt = [
    "hilt",
    "hilt-navigation",
]

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
